/* Uploaded images are browser-local Data URLs and do not use the image optimization service. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import Script from "next/script";

export default function Home() {
  return (<>

<header className="nav"><Link className="brand" href="/" aria-label="衣境 AI 首页"><span className="logo">✦</span><strong>衣境 <span>AI</span></strong></Link><span className="nav-caption"><span className="nav-active">创作工作台</span><span className="nav-divider"></span>让风格，自由发生</span><div className="account"><button id="avatar" className="avatar" aria-label="打开账户菜单" aria-expanded="false" aria-controls="account-menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="3.5"></circle><path d="M5 21v-2a7 7 0 0 1 14 0v2"></path></svg></button><div id="account-menu" className="menu" hidden={true}><p id="account-label">欢迎来到衣境 AI</p><button id="login-entry">登录 / 注册 <span>↗</span></button><button id="logout" hidden={true}>退出登录</button></div></div></header>
<main>
<section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="dot"></span> AI VIRTUAL TRY-ON STUDIO</span><h1>AI 模型服装替换<span className="hero-subtitle">让下一套穿搭，<em>即刻有灵感。</em></span></h1><p>一张人物照片，一件心仪的服装。<br />在这里，探索属于你的下一种风格。</p><div className="steps"><span><b>01</b> 上传图片</span><i></i><span><b>02</b> AI 换装</span><i></i><span><b>03</b> 查看结果</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-orbit"></div><div className="art-card art-person"><span>THE MUSE</span><svg viewBox="0 0 120 150" fill="none"><circle cx="60" cy="30" r="15"></circle><path d="M39 55Q60 46 81 55L94 104L79 108L74 77V137H47V77L41 108L26 104Z"></path></svg><small>01 / 人物</small></div><div className="art-card art-clothing"><span>THE LOOK</span><svg viewBox="0 0 120 150" fill="none"><path d="M40 30L14 47L27 71L39 63V126H81V63L93 71L106 47L80 30Q60 53 40 30Z"></path><path d="M49 34Q60 43 71 34"></path></svg><small>02 / 风格</small></div><div className="art-spark">✦</div><span className="art-caption">A NEW LOOK. A NEW POSSIBILITY.</span></div></section><div className="studio-grid">
<section className="workspace" aria-label="AI 换装操作区"><div className="workspace-head"><div><span className="tiny-label">01 — 上传素材</span><h2>打造你的新造型</h2></div><span className="demo-tag">✦ 演示模式</span></div>
<div className="uploads">
<article className="upload-card"><div className="card-heading"><h3>人物图片</h3><span>01 / PERSON</span></div><label className="dropzone" id="person-zone" htmlFor="person-input"><input id="person-input" type="file" accept="image/jpeg,image/png,image/webp" /><div className="upload-prompt"><span className="upload-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="12" cy="7" r="3"></circle><path d="M5 21v-3a7 7 0 0 1 14 0v3"></path></svg></span><strong>上传人物 / 模特照片</strong><span>点击选择，或拖拽图片到这里</span><small>JPG、PNG、WebP · 最大 5MB</small></div><img id="person-preview" hidden={true} alt="人物图片预览" /></label><div className="file-line"><span id="person-name">建议使用清晰、完整的人物正面照片</span><button type="button" id="person-remove" hidden={true}>移除</button></div></article>
<article className="upload-card"><div className="card-heading"><h3>服装图片</h3><span>02 / CLOTHING</span></div><label className="dropzone" id="clothing-zone" htmlFor="clothing-input"><input id="clothing-input" type="file" accept="image/jpeg,image/png,image/webp" /><div className="upload-prompt"><span className="upload-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0Z"></path></svg></span><strong>上传想要替换的服装</strong><span>点击选择，或拖拽图片到这里</span><small>JPG、PNG、WebP · 最大 5MB</small></div><img id="clothing-preview" hidden={true} alt="服装图片预览" /></label><div className="file-line"><span id="clothing-name">建议使用背景简洁的服装展示图片</span><button type="button" id="clothing-remove" hidden={true}>移除</button></div></article>
</div><div className="action"><button id="generate" className="primary" disabled={true}><span>✦</span> 开始 AI 换装 <span>→</span></button><p id="status" role="status" aria-live="polite">上传两张图片，即可开始体验</p></div></section>
<section className="results" aria-labelledby="result-title"><div className="result-heading"><div><span className="tiny-label">02 — 预览作品</span><h2 id="result-title">AI 生成结果</h2></div><span id="result-tag">等待生成</span></div><div id="result-empty" className="empty"><div className="result-frame"><span>✧</span><i></i><i></i><i></i><i></i></div><h3>新的风格，即将在这里呈现</h3><p>选好人物与服装，<br />剩下的，交给你的灵感。</p></div><div id="result-output" hidden={true}><div className="result-note" id="result-note"></div><img id="result-image" alt="演示结果：上传的人物原图" /></div></section>
</div><p className="privacy"><span aria-hidden="true">◇</span> 图片仅用于本次演示，不保存到服务器。当前尚未接入真实 AI 换装模型。</p>
</main><footer><span>衣境 AI <span className="footer-dot">/</span> 创意，从一件衣服开始</span><span>为创意留出空间。</span></footer>
<dialog id="login-dialog"><form id="login-form"><button type="button" id="close-dialog" className="close" aria-label="关闭登录窗口">×</button><span className="logo">✦</span><h2>欢迎登录衣境 AI</h2><p className="dialog-intro">无需登录，也可以自由体验换装流程。</p><label htmlFor="username">用户名</label><input id="username" name="username" autoComplete="username" maxLength={100} required={true} /><label htmlFor="password">密码</label><input id="password" name="password" type="password" autoComplete="current-password" maxLength={200} required={true} /><p id="login-error" role="alert"></p><button className="primary" id="login-submit">登录</button><p className="register-note">注册功能即将开放 · 当前可使用测试账号登录</p></form></dialog>

<Script src="/app.js" strategy="afterInteractive" />
</>);
}

