export type Language = 'zh' | 'en';
export const copy = {
  zh: {
    brand: '衣搭灵感', studio: '创作工作台', privacy: '隐私与安全', terms: '服务条款', language: '语言 / Language', login: '登录', logout: '退出登录',
    eyebrow: '你的专属穿搭空间', heading: '下一套穿搭，', accent: '从灵感开始。', intro: '一张人物照片，一件心仪的服装。轻松整理搭配灵感，探索你的下一种风格。', localChip: '本地预览 · 图片不上传', exportChip: '搭配板 · 一键下载',
    title: 'AI 换装工作台', demo: '演示版', demoNote: '当前可制作搭配板与原图预览；真实 AI 换装尚未开放。', step1: '准备素材', step2: '制作搭配板', step3: '查看与下载', materials: '你的穿搭素材', ready: '已就绪',
    person: '人物照片', clothing: '服装图片', personHelp: '建议使用清晰的正面照片', clothingHelp: '建议使用背景简洁的服装图片', upload: '选择图片', replace: '更换图片', remove: '移除', drop: '点击选择或拖拽图片到这里', formats: 'JPG / PNG / WebP · 每张不超过 5MB', pending: '待选择', reading: '读取中…', uploaded: '已选择',
    consent: '我拥有这些图片的使用权，并同意本次处理。', readPrivacy: '阅读隐私说明', samples: '使用示例素材', sampleNote: '没有图片？先用插画示例体验操作。', preview: '制作本地搭配板', serverPreview: '服务器演示预览', serverHelp: '登录后可验证服务器图片处理，结果为人物原图。', preparing: '正在处理…', needPerson: '请先选择人物照片', needClothing: '请先选择服装图片', needConsent: '请先勾选图片处理授权',
    result: '作品预览', empty: '留一个位置，给新的灵感', emptyHelp: '选择人物与服装素材，制作你的搭配板。', board: '搭配板', original: '人物原图', resultNote: '这是素材对照搭配板，不是 AI 换装结果。', originalNote: '这是人物原图预览，未进行 AI 换装。', download: '下载图片', clear: '清除全部图片', clearHelp: '图片仅临时保留，每 30 分钟自动清除。下载的文件由你自行管理。',
    initial: '选择两张图片，或使用示例素材开始体验。', selected: '素材已就绪，授权后即可制作搭配板。', cleared: '已清除所有素材、预览和授权。', expired: '临时图片已到期清除。', localDone: '搭配板已完成，图片未上传，可切换查看人物原图。', serverDone: '服务器演示完成，今日剩余 {count} 次。结果为人物原图。', invalid: '请选择 5MB 以内的有效 JPG、PNG 或 WebP 图片。', pixels: '图片超过 2000 万像素，请缩小后重试。', imageError: '图片无法读取，请选择有效的静态图片。', exportError: '预览制作失败，请重试或换一张图片。',
    loginTitle: '欢迎回到衣搭灵感', loginIntro: '使用授权账号登录。无需登录也可以制作本地搭配板。', username: '用户名', password: '密码', showPassword: '显示密码', hidePassword: '隐藏密码', close: '关闭', loggingIn: '正在登录…', loggedIn: '登录成功，可以使用服务器演示预览。', signedOut: '已退出登录，本地素材仍然保留。', checking: '正在检查账号状态…', unavailable: '当前未开放账号登录；你可以直接体验本地搭配板。', unknown: '暂时无法连接登录服务，请重试。', retry: '重新检查', cookieError: '登录未能保持，请允许本站 Cookie；线上网站需使用 HTTPS。', authNeeded: '请先登录授权账号，再提交服务器处理。',
    privacyTitle: '你的照片，由你掌控', privacyIntro: '透明的处理方式，明确的使用边界。', updated: '更新日期：2026 年 10 月 3 日 · 当前演示版', privacyLocal: '本地预览', privacyLocalText: '选择图片、制作搭配板和本地下载均在浏览器完成，不向服务器或第三方发送图片。语言偏好保存在当前浏览器，不保存照片。', privacyServer: '服务器演示', privacyServerText: '仅在登录并勾选授权后，点击服务器演示预览才会将两张图片发送至本站。服务器验证格式、清除元数据并返回人物原图，不调用第三方 AI。', privacyDelete: '保存与删除', privacyDeleteText: '服务器不将图片写入磁盘、数据库或公共目录。页面每 30 分钟自动清除临时图片，也可以手动清空。下载文件由你自行管理。', privacyAccount: '账号与用途', privacyAccountText: '仅保存配置的账号名称和加盐密码哈希。登录会话最多保留两小时。私人照片不用于训练、广告或公开展示。当前不支持注册、支付或订单。', contact: '联系运营方', noContact: '隐私联系渠道尚未配置，当前仅适合受限演示。', back: '返回创作工作台',
    termsTitle: '服务条款（演示版）', termsText: '本站提供本地搭配板和授权账号的服务器原图预览，不提供真实 AI 换装或付费服务。仅上传本人或已获授权的照片，不得用于侵权、骚扰或违法用途。', limits: '服务器演示每进程每分钟最多 5 次，每个 UTC 日期最多 20 次；重启会重置配额。本地搭配板不占用服务器配额。接入真实 AI 或支付前会更新说明并重新征得同意。',
    networkError: '网络连接失败，请检查网络后重试。', timeout: '请求超时，请稍后重试。', invalidOrigin: '登录服务地址配置不匹配，请联系管理员。', wrongPassword: '用户名或密码错误，请重新输入。', rateLimited: '请求过于频繁，请稍后重试。', invalidRequest: '请求格式无效，请刷新后重试。', quota: '今日服务器演示次数已用完，请明天再试。', serverBusy: '服务器正在处理其他图片，请稍后重试。', footer: '给风格更多可能',
  },
  en: {
    brand: 'Style Muse', studio: 'Creative studio', privacy: 'Privacy & safety', terms: 'Terms of use', language: 'Language / 语言', login: 'Sign in', logout: 'Sign out',
    eyebrow: 'YOUR PERSONAL STYLE STUDIO', heading: 'Your next look,', accent: 'starts with inspiration.', intro: 'A portrait. A piece you love. Bring your style ideas together and explore your next look.', localChip: 'Local preview · No uploads', exportChip: 'Style board · Easy download',
    title: 'AI try-on studio', demo: 'Demo', demoNote: 'Create a style board or preview your original photo. AI try-on is not available yet.', step1: 'Add your images', step2: 'Create a board', step3: 'View & download', materials: 'Your style materials', ready: 'ready',
    person: 'Portrait photo', clothing: 'Clothing image', personHelp: 'A clear, front-facing photo works best', clothingHelp: 'Choose clothing against a simple background', upload: 'Choose image', replace: 'Replace image', remove: 'Remove', drop: 'Choose an image or drag it here', formats: 'JPG / PNG / WebP · Up to 5MB each', pending: 'Not selected', reading: 'Reading…', uploaded: 'Selected',
    consent: 'I have permission to use these images and consent to this processing.', readPrivacy: 'Read privacy details', samples: 'Try sample images', sampleNote: 'No photos handy? Explore with illustration samples.', preview: 'Create local style board', serverPreview: 'Server demo preview', serverHelp: 'Sign in to test server processing. The result is your original portrait.', preparing: 'Processing…', needPerson: 'Choose a portrait first', needClothing: 'Choose clothing first', needConsent: 'Confirm image processing consent',
    result: 'Your preview', empty: 'Make room for a new idea', emptyHelp: 'Add a portrait and clothing image to create your style board.', board: 'Style board', original: 'Original portrait', resultNote: 'This board compares your materials. It is not an AI try-on result.', originalNote: 'This is your original portrait. No AI try-on has been applied.', download: 'Download image', clear: 'Clear all images', clearHelp: 'Temporary images are cleared every 30 minutes. You manage any downloaded files.',
    initial: 'Choose two images or try the samples to get started.', selected: 'Images are ready. Confirm consent to create your board.', cleared: 'All materials, previews and consent have been cleared.', expired: 'Temporary images have expired and been cleared.', localDone: 'Your board is ready. No images were uploaded. Switch to view your original portrait.', serverDone: 'Server demo complete. {count} previews left today. The result is the original portrait.', invalid: 'Choose a valid JPG, PNG or WebP image up to 5MB.', pixels: 'This image exceeds 20 megapixels. Resize it and try again.', imageError: 'Unable to read this image. Choose a valid still image.', exportError: 'Could not create the preview. Try again or choose another image.',
    loginTitle: 'Welcome back to Style Muse', loginIntro: 'Sign in with an authorized account. Local style boards work without signing in.', username: 'Username', password: 'Password', showPassword: 'Show password', hidePassword: 'Hide password', close: 'Close', loggingIn: 'Signing in…', loggedIn: 'Signed in. You can now use the server demo.', signedOut: 'Signed out. Your local materials are still here.', checking: 'Checking account status…', unavailable: 'Account sign-in is not available yet. You can still create a local style board.', unknown: 'Unable to connect to sign-in. Please retry.', retry: 'Check again', cookieError: 'Your session could not be saved. Allow cookies for this site; hosted sites require HTTPS.', authNeeded: 'Sign in with an authorized account before sending images to the server.',
    privacyTitle: 'Your photos. Your control.', privacyIntro: 'Clear processing. Clear boundaries.', updated: 'Updated October 3, 2026 · Current demo version', privacyLocal: 'Local preview', privacyLocalText: 'Image selection, style boards and local downloads run in your browser. No images are sent to a server or third party. Only your language preference is saved in this browser, never your photos.', privacyServer: 'Server demo', privacyServerText: 'Images are sent to this site only when you sign in, confirm consent and select Server demo preview. The server validates images, removes metadata and returns your original portrait. No third-party AI is used.', privacyDelete: 'Storage & deletion', privacyDeleteText: 'The server does not write images to disk, a database or a public folder. Temporary browser images are cleared every 30 minutes or when you choose Clear all images. You manage downloaded files.', privacyAccount: 'Accounts & permitted use', privacyAccountText: 'Only a configured username and salted password hash are stored. Sessions last up to two hours. Private images are not used for training, advertising or public display. Registration, payments and orders are not available.', contact: 'Contact the operator', noContact: 'A privacy contact has not been configured. This version is suitable only for a restricted demo.', back: 'Back to creative studio',
    termsTitle: 'Terms of use (demo)', termsText: 'This site offers local style boards and server previews for authorized accounts. It does not offer AI try-on or paid services. Only use photos of yourself or photos you have permission to process. Do not use this service for infringement, harassment or unlawful purposes.', limits: 'The server demo allows up to 5 requests per minute and 20 per UTC day per process. Restarting resets the quota. Local boards do not use server quota. Details and consent will be updated before AI or payments are introduced.',
    networkError: 'Connection failed. Check your network and try again.', timeout: 'The request timed out. Please try again.', invalidOrigin: 'The sign-in service address is misconfigured. Contact the administrator.', wrongPassword: 'Incorrect username or password. Please try again.', rateLimited: 'Too many requests. Please try again later.', invalidRequest: 'Invalid request. Refresh the page and try again.', quota: 'The daily server demo limit has been reached. Please try tomorrow.', serverBusy: 'The server is processing another image. Please try again shortly.', footer: 'More possibilities for your style',
  },
} as const;
export type CopyKey = keyof typeof copy.zh;
